### ISSUE TITLE
Allow an app's .terra.yml file to override or extend the generated docker-compose.yml

### ISSUE THREAD

**Issue by jonpugh** [terra-ops/terra-cli#21]
The .terra.yml file could have something like this

```
compose_file: docker-compose.yml
```

or 

```
compose:
  redis:
    image: redis
  app:
    links:
    -  redis
```

which would automatically merge with the generated compose.yml file.

Feedback welcome.

**Comment by xendk** [comment]
I'd suggest just using the `docker-compose.yml` file if it exists.

We'd still need the option of setting it in the `.terra.yml` file in case you want to use a different file name. And setting it to null ("~") could make terra ignore a project `docker-compose.yml` and fall back its own.

**Comment by jonpugh** [comment]
First use case was to add a container linked to the app container, I've successfully added code to do this:

```
docker-compose:
  app_services:
    redis:
      image: redis
```

Because we need to always link these addon services to the app container, I called the property `app_services`.  These are added directly to the `docker-compose.yml` file, and the service is linked to the app container automatically.

There's still more work to do to allow apps to totally override their docker setup.  I welcome others to help on this, as it's not a priority for me at this point.
