### ISSUE TITLE
Implement Cron

### ISSUE THREAD

**Issue by jonpugh** [terra-ops/terra-cli#72]
We need a nice common way of running cron.

I do not know yet if it would be best to run it on the host or in the container.  

The drush container could have cron setup within it.

Let's take inspiration from platform.sh: https://github.com/platformsh/platformsh-examples/blob/drupal/7.x/.platform.app.yaml#L42

```
# The configuration of scheduled execution.
crons:
    drupal:
        spec: "*/20 * * * *"
        cmd: "cd public ; drush core-cron"
```
