### ISSUE TITLE
Running environment:enable on a non-existent env causes fatal problems in ~/.terra/terra

### ISSUE THREAD

**Issue by jlyon** [terra-ops/terra-cli#78]
I seem to be having issues cloning repos occasionally #79.

After I do this, I will instinctively run

```
terra e:e drupal local
```

Which will try to run docker build and will write this to the `~/.terra/terra`

```
        environments:
            '':
                url: 'http://localhost:32782'
                name: null                                                                                                                          
```

Any future terra commands give a fatal error until I manually edit~/.terra/terra .

```
  [Exception]                                                                                                                        
  There is an error with your configuration: The child node "path" at path "project.apps.popline.environments." must be configured.                                                                                                                                    
```

Ideally, we should check to see that the environment exists before enabling it.
