### ISSUE TITLE
Error after installing new version of terra

### ISSUE THREAD

**Issue by frankcarey** [terra-ops/terra-cli#97]
I got an error:

There is an error with your configuration: The child node "domains" at path "project.apps.drupal7.environments.local" must be configured.

I had to create a new item `domains: [ ]` in ~/.terra/terra yaml file to get the `terra status` to work.

Final result looks like this:

``` Yaml
    drupal7:
        name: drupal7
        description: ''
        repo: 'git@github.com:terra-ops/example-drupal.git'
        host: 192.168.10.10
        environments:
            local:
                name: local
                path: /Users/fcarey/Apps/drupal7/local
                document_root: ''
                url: ''
                version: master
                domains: [ ]
```
